[package]
name = "voe-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
chaser-oxide = "0.1" # або "0.1.2", яка зараз є актуальною
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
anyhow = "1.0"
