name: Standard Puppeteer Scraper

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  take-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '25'

      - name: Install Dependencies
        run: |
          # Ініціалізуємо пакет і ставимо Puppeteer зі Stealth-плагіном
          npm init -y
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
          
          # Встановлюємо системні залежності для Chrome та Xvfb
          sudo apt-get update
          sudo apt-get install -y xvfb libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 libxss1 libxtst6 libnss3 libatk-bridge2.0-0 libgtk-3-0 

      - name: Run Puppeteer with Xvfb
        # Запускаємо скрипт у віртуальному моніторі
        run: xvfb-run --auto-servernum node scraper.js

      - name: Upload Screenshot Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: voe-page-screenshot
          path: voe_detailed.png
          retention-days: 5
